version: '2'
services:
    coinoffline-app:
        image: coinoffline
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://coinoffline-mysql:3306/coinoffline?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    coinoffline-mysql:
        extends:
            file: mysql.yml
            service: coinoffline-mysql
